removed warning banner & user balances from proposal tab
dOrgTech/homebase-app pull request #454
Opened 2023-01-10 22:09 UTC by fabiolalombardim

2023-01-10 22:21 UTC, Man-Jain requested changes
No need to comment out the changes we can completely remove them

2023-01-10 22:23 UTC, Man-Jain requested changes
No need to comment out the changes we can completely remove them

2023-01-11 11:27 UTC, EightRice approved these changes

2023-01-11 11:40 UTC, Man-Jain approved these changes

2023-01-11 11:41 UTC, merged