token deployment flow
dOrgTech/homebase-app pull request #506
Opened 2023-02-26 11:00 UTC by fabiolalombardim

Closes #497

2023-03-16 16:19 UTC, fabiolalombardim commented
Closes #512

2023-04-19 12:12 UTC, Man-Jain commented on src/modules/creator/steps/Template.tsx
> +          <BoxTitle color="textSecondary">Lite DAO</BoxTitle>
The lite dao shouldn't be here

2023-04-19 12:12 UTC, Man-Jain commented on src/modules/explorer/components/ProposalForm.tsx
> +  "lite": []
same here

2023-04-19 12:12 UTC, Man-Jain commented on src/modules/creator/state/types.ts
> +export type DAOTemplate = "lambda" | "lite" | ""
LIte shouldn't be here

2023-04-21 10:09 UTC, Man-Jain requested changes
![Screenshot 2023-04-21 at 3 38 03 PM](https://user-images.githubusercontent.com/12700384/233609790-372081e6-45ae-43ff-a57a-9b85c9ee62d6.png)

Can we redirect user directly to the Step two instead of showing this, this is a big unnecessary.

2023-04-21 10:13 UTC, Man-Jain commented
![Screenshot 2023-04-21 at 3 41 56 PM](https://user-images.githubusercontent.com/12700384/233610737-ffd7b342-3d1d-41f5-b3de-967e93bcb5b9.png)

Let's put a label besides the Token Address and make it super clear that this is the token Address 

Something Like 

Your Token Address - KT1A4bpidDyfsSBzac1tka7U9BS65FCK3HrG

2023-05-23 18:12 UTC, Man-Jain commented
Initial token distribution
- Should not be able to allocate tokens to the same address multiple times
- On allocating more than the total supply, the page hangs and you cannot change the fields

2023-05-25 19:38 UTC, Man-Jain approved these changes

2023-05-25 19:38 UTC, merged