ui upgrades added
dOrgTech/homebase-app pull request #588
Opened 2023-06-06 15:23 UTC by fabiolalombardim

Closes #583

2023-06-28 23:16 UTC, thenerdcat approved these changes

2023-06-29 00:49 UTC, Man-Jain approved these changes

2023-06-29 00:55 UTC, Man-Jain requested changes
Are the buttons supposed to be same everywher ?

2023-07-05 08:11 UTC, fabiolalombardim commented
@Man-Jain there's an specific issue for buttons

2023-07-05 18:16 UTC, Man-Jain approved these changes

2023-07-19 19:40 UTC, thenerdcat requested changes
Comments left on discord

2023-07-24 20:31 UTC, thenerdcat approved these changes

2023-07-28 18:49 UTC, closed without merging