Votes grouping
dOrgTech/homebase-app pull request #832
Opened 2024-04-14 02:32 UTC by fabiolalombardim

Closes #787 

<img width="1482" alt="Captura de pantalla 2024-04-14 a las 4 32 08" src="https://github.com/dOrgTech/homebase-app/assets/37227394/f7da355b-9d56-4c92-89eb-39b2e99ca027">

2024-04-14 10:08 UTC, fabiolalombardim commented
<img width="1337" alt="Captura de pantalla 2024-04-14 a las 12 08 20" src="https://github.com/dOrgTech/homebase-app/assets/37227394/57a3248d-441f-4a97-bf96-745edef6f5ad">
Css added & responsive table

2024-04-27 09:41 UTC, fabiolalombardim commented
<img width="1202" alt="Captura de pantalla 2024-04-27 a las 11 39 56" src="https://github.com/dOrgTech/homebase-app/assets/37227394/5cf1fa5f-5d80-4395-b3d1-d7014fa66958">

Adding grouping solution to CSV file @ashutoshpw @EightRice @Man-Jain

2024-05-12 21:15 UTC, Man-Jain commented on package.json
> +    "typescript": "5.4.0-beta"
We shouldn't be using a beta version of typescript.

2024-05-12 21:17 UTC, Man-Jain commented on src/modules/lite/explorer/components/VoteDetails.tsx
> +                decimals={tokenData?.decimals ? tokenData?.decimals : ""}
should there be a isXTZ check here for 6 decimals ?

2024-05-12 21:24 UTC, Man-Jain reviewed
Only 2 little comments. Rest ready to merge

2024-05-12 21:27 UTC, Man-Jain commented on src/modules/lite/explorer/components/VoteDetails.tsx
>            decimals={tokenData?.decimals ? tokenData?.decimals : ""}
Same here

2024-05-14 21:29 UTC, Man-Jain requested changes
Can be merged after the decimal fix

2024-05-27 11:46 UTC, Man-Jain commented on src/modules/lite/explorer/components/VoteDetails.tsx
> +                decimals={tokenData?.decimals ? tokenData?.decimals : ""}
@fabiolalombardim Do we not need the decimal change here too ?

```decimals={tokenData?.decimals ? tokenData?.decimals : "6"```

2024-05-28 00:42 UTC, Man-Jain commented on src/modules/lite/explorer/components/VoteDetails.tsx
> +          decimals={tokenData?.decimals ? tokenData?.decimals : "6"}
I'm not sure if it's the best idea to default the decimal to 6, I'm not sure what we can do here but decimals = 6 should only be the case with isXTZ

2024-09-26 12:48 UTC, Man-Jain approved these changes

2024-10-29 18:39 UTC, merged