WIP: Offchain DAOs on Etherlink
dOrgTech/homebase-app pull request #862
Opened 2024-07-16 16:23 UTC by ashutoshpw

- Implementing WAGMI for Etherlink Login
- Changing useTezos hook to handle login with Etherlink
- Changing Validation options when Etherlink is active.

2024-09-03 19:16 UTC, Man-Jain commented on src/modules/common/ConnectWalletButton.tsx
> +        Connect Wallet C
Should `C` be here ?

2024-09-26 07:59 UTC, Man-Jain requested changes

2024-10-01 17:05 UTC, ashutoshpw commented on src/modules/common/ConnectWalletButton.tsx
> +        Connect Wallet C
Removed.

2024-10-01 17:05 UTC, ashutoshpw commented on src/modules/common/ConnectWalletButton.tsx
> +      Connect Wallet A
Removed.

2024-10-01 17:06 UTC, ashutoshpw commented on src/modules/creator/deployment/steps/Ownership.tsx
> +                      window.open(`https://remix.ethereum.org/`)
We are building a deployer right here:
https://github.com/dOrgTech/homebase-app/pull/868

For the time being, replaced this with : https://www.cookbook.dev/contracts/simple-token

2024-10-06 20:03 UTC, Man-Jain commented
@ashutoshpw Are these comment still WIP or done ?

2024-10-08 11:49 UTC, ashutoshpw commented
@Man-Jain This is still in WIP, I will re-request review once all the issues as fixed.

2024-11-05 18:12 UTC, EightRice approved these changes

2024-11-06 11:08 UTC, Man-Jain approved these changes

2024-11-06 11:11 UTC, merged